apiVersion: v1
kind: Secret
metadata:
  name: bw-auth-token
  namespace: authentik
type: Opaque
stringData:
  token: XXXXX
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/created-by: sm-operator
  name: authentik
  namespace: authentik
spec:
  organizationId: eabfd0f9-cc8a-414c-a8ce-b3cf016546cc
  secretName: authentik
  map:
    - bwSecretId: f8e06af9-a7fa-467d-9e90-b3cf0165f30c
      secretKeyName: secret-key
    - bwSecretId: 968fc784-5b9e-46ea-9460-b3cf0166177c
      secretKeyName: pg-password
    - bwSecretId: 06740ca7-0316-4684-9a6a-b3cf016631b5      
      secretKeyName: client-id
    - bwSecretId: f3d9d500-7b6e-446c-8664-b3cf0166479f
      secretKeyName: client-secret
  authToken:
    secretName: bw-auth-token
    secretKey: token

