---
apiVersion: v1
kind: Namespace
metadata:
  name: actual-budget
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: community-charts
  namespace: actual-budget
spec:
  repo: https://community-charts.github.io/helm-charts
  chart: actualbudget
  targetNamespace: planka
  version: "1.8.6"
  valuesContent: |-
    login:
      allowedLoginMethods: ["openid"]
      method: "openid"
      openid:
        discoveryUrl: ""
        tokenExpiration: 3600
        existingSecret:
          name: "actualbudget-openid-secret"
          clientIdKey: "XXXXX"
          clientSecretKey: "XXXXX"

    storageClass: "actualbudget"
    accessModes:
      - ReadWriteOnce

    persistence:
      enabled: true
      size: 10Gi
      existingClaim: "actualbudget"
