apiVersion: v1
kind: Namespace
metadata:
  name: cnpg
---
apiVersion: helm.cattle.io/v1
king: HelmChart
metadata:
  name: cnpg
  namespace: cnpg
spec:
  repo: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  targetNamespace: cnpg
  version: "0.27.0"
