apiVersion: v1
kind: Namespace
metadata:
  name: seafile
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: datamate
  namespace: seafile
spec:
  repo: https://datamate-rethink-it.github.io/seafile-helm
  chart: seafile
  targetNamespace: seafile
  version:
  valuesContent: |-
    timezone: America/Denver

    seafileConfig:
      # For admin logins
      adminCredentiaSecret: "XXXXX"
      # Secret for seahub
      seahubSecretKeySecret: "XXXXX"
      # Secret for S3 storageClass
      storageClassSecret: "XXXXX"
      # Secret for SQL DB
      mariadbCredentialSecret: "XXXXX"

      hostname: cloud.ff.cc
      
      ingress:
        className: traefik
        enableTls: false

      mariadb:
        host: mariadb.ff.home
        port: 9100
        user: seafile

      volumes:
        data:
          storageClass: seafile-s3
      
      extraEnv:

    elasticsearch:
      enabled: false

    mariadb-galera
      enabled: false

    minio:
      enabled: false


