apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-backup
  namespace: cnpg
  labels:
    app: cnpg-backup
spec:
  s3:
---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnpg-backup
  namespace: cnpg
  labels:
    app: cnpg-backup
spec:
  # AKS: default,managed-premium
  # GKE: standard
  # EKS: gp2 (custom)
  # Rook: rook-ceph-block,rook-ceph-fs
  storageClassName: garage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
