apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: plugin-barman-cloud
  namespace: kube-system
spec:
  repo: https://cloudnative-pg.io/charts/
  chart: cloudnative-pg
  targetNamespace: cnpg-system
