apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudflare-r2-store
spec:
  configuration:
    destinationPath: s3://backups-dev/
    endpointURL: http://cloudflare
    retentionPolicy: "30d"
    s3Credentials:
      accessKeyId:
        name: cloudflare-r2
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cloudflare-r2
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
