apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-1
  namespace: cnpg-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 3

  storage:
    size: 10Gi

  bootstrap:
#    initdb:
#      import:
#        type: monolith
#        databases:
#          - "*"
#        roles:
#          - "*"
#        source:
#          externalCluster: lxc-pg
    recovery:
      source: cloudflare-r2-store

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cloudflare-r2-store

  externalClusters:
    - name: cloudflare-r2-store
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cloudflare-r2-store
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-1
  namespace: cnpg-system
spec:
  schedule: "0 0 0 * * *"  # At midnight every day
  backupOwnerReference: cluster
  cluster:
    name: cluster-1
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
