apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "$EMAIL"
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            email: supercomputer74@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fullerfamily-tls
  namespace: cert-manager
spec:
  secretName: fullerfamily-tls
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
  commonName: fullerfamily.cc
  dnsNames:
    - fullerfamily.cc
    - "*.fullerfamily.cc"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 062625-tls
  namespace: cert-manager
spec:
  secretName: 062625-tls
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
  commonName: 062625.xyz
  dnsNames:
    - 062625.xyz
    - "*.062625.xyz"
---

