apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: envoy-gateway
  namespace: kube-system
spec:
  chart: oci://docker.io/envoyproxy/gateway-helm
  version: v1.6.2
  targetNamespace: envoy-gateway-system
  createNamespace: true

