apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway-class
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway-class
  infrastructure:
    labels:
      app: envoy-gateway
  listeners:
    - name: https-fullerfamily
      protocol: HTTPS
      port: 443
      hostname: "*.fullerfamily.cc"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: fullerfamily-tls
            kind: Secret
    - name: https-062625
      protocol: HTTPS
      port: 443
      hostname: "*.062625.xyz"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: 062625-tls
            kind: Secret
