apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: 0.14.5
  targetNamespace: metallb-system
  valuesContent: |-
    controller:
      enabled: true
    speaker:
      enabled: true

    # Example: configure L2 mode
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 10.12.30.150-10.12.30.250

