apiVersion: v1
kind: Secret
metadata:
  name: bw-auth-token
  namespace: planka
type: Opaque
stringData:
  token: BW-AUTH-TOKEN
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/created-by: sm-operator
  name: planka
  namespace: planka
spec:
  organizationId: eabfd0f9-cc8a-414c-a8ce-b3cf016546cc
  secretName: planka
  map:
    - bwSecretId: f8e06af9-a7fa-467d-9e90-b3cf0165f30c
      secretKeyName: key
    - bwSecretId: 8c3d3387-f0a7-494a-9aef-b3d8002d2653
      secretKeyName: uri
    - bwSecretId: 47542a65-6739-4691-9ccf-b3d7016a6c8b      
      secretKeyName: clientId
    - bwSecretId: fa8769f1-4c06-46e3-adef-b3d7016aa212
      secretKeyName: clientSecret
  authToken:
    secretName: bw-auth-token
    secretKey: token


