apiVersion: v1
kind: Endpoints
metadata:
  name: garage-s3-endpoints
subsets:
- addresses:
  - ip: 10.12.40.111
  - ip: 10.12.40.121
  - ip: 10.12.40.131
  ports:
  - port: 3900
---
apiVersion: v1
kind: Service
metadata:
  name: garage-s3-lb
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: none
  ports:
    - port: 3900
      targetPort: 3900
