apiVersion: v1
kind: Secret
metadata:
  name: bw-auth-token
  namespace: kube-system
type: Opaque
stringData:
  token: BW-AUTH-TOKEN
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/created-by: sm-operator
  name: csi-s3-secret
  namespace: kube-system
spec:
  organizationId: eabfd0f9-cc8a-414c-a8ce-b3cf016546cc
  secretName: csi-s3-secret
  map:
    - bwSecretId: 0abc6763-f831-4c93-9389-b3d70189c3f8
      secretKeyName: accessKeyId
    - bwSecretId: 0abc6763-f831-4c93-9389-b3d70189c3f8
      secretKeyName: secretAccessKey
    - bwSecretId: 0abc6763-f831-4c93-9389-b3d70189c3f8
      secretKeyName: endpoint
  authToken:
    secretName: bw-auth-token
    secretKey: token
