apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-nfs-pv
  namespace: nextcloud
spec:
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: svr.ff.home
    path: "/mnt/storage/cloud"
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: immich
spec:
  volumeName: nextcloud-data-nfs-pv
  storageClassName: manual
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteMany
