apiVersion: v1
kind: Secret
metadata:
  name: bw-auth-token
  namespace:  nextcloud
type: Opaque
stringData:
  token: BW-SECRET-TOKEN
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/created-by: sm-operator
  name: nextcloud
  namespace: nextcloud
spec:
  organizationId: eabfd0f9-cc8a-414c-a8ce-b3cf016546cc
  secretName: nextcloud
  map:
    - bwSecretId: a560d37c-306c-4371-a655-b3d8011314b6
      secretKeyName: login-username
    - bwSecretId: a560d37c-306c-4371-a655-b3d8011314b6
      secretKeyName: login-password
    - bwSecretId: a560d37c-306c-4371-a655-b3d8011314b6
      secretKeyName: pg-password
  authToken:
    secretName: bw-auth-token
    secretKey: token

