apiVersion: v1
kind: Secret
metadata:
  name: bw-auth-token
  namespace:  nextcloud
type: Opaque
stringData:
  token: BW-SECRET-TOKEN
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/created-by: sm-operator
  name: nextcloud
  namespace: nextcloud
spec:
  organizationId: eabfd0f9-cc8a-414c-a8ce-b3cf016546cc
  secretName: nextcloud
  map:
    - bwSecretId: 0cdd88a2-e4ab-4c1f-860b-b3de0054292c
      secretKeyName: login-username
    - bwSecretId: 122c9bfe-e133-479f-8c97-b3de00543663
      secretKeyName: login-password
    - bwSecretId: 275e94db-fe02-4efb-9e56-b3de00541aff
      secretKeyName: pg-password
    - bwSecretId: 6917098e-225e-4c5c-be63-b3de002a9368
      secretKeyName: s3-access-key
    - bwSecretId: 69f700b5-6a8a-4c98-8da1-b3de002a2ffb
      secretKeyName: s3-secret-key
  authToken:
    secretName: bw-auth-token
    secretKey: token

